namespace RadLine;

public enum SubmitAction {
    Cancel,
    Delete,
    Backspace,
    Submit,
    NewLine,
    MoveLeft,
    MoveRight,
    MoveToPreviousWord,
    MoveToNextWord,
    MoveLineStart,
    MoveLineEnd,
    MoveTextStart,
    MoveTextEnd,
    MoveUp,
    MoveDown,
    MovePageUp,
    MovePageDown,
    MoveTop,
    MoveBottom,
    PreviousHistory,
    NextHistory,
}
